### ISSUE TITLE
Publish Date needs to count for other timezones/entry methods

### ISSUE THREAD

**Issue by simondavies** [ericlbarnes/wardrobe#41]
When experimenting with this I found the publish date input pop up, and as you can handle written dates 'Next Friday', 'Next Thursday 10am' and also the format of 'MM/DD/YY' I tend to have enter a UK date format as 'DD/MM/YY' say 14/07/13 but this caused the form to error on submission with the object:object

**Comment by ericlbarnes** [comment]
This is actually because I am using php's [strtotime](http://us3.php.net/strtotime). However it does say this: 

> Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed.
> To avoid potential ambiguity, it's best to use ISO 8601 (YYYY-MM-DD) dates or DateTime::createFromFormat() when possible.

So by using a dash (-) or dot (.) as a separator it should work for you. DD-MM-YY or DD.MM.YY

**Comment by simondavies** [comment]
thanks for the reply, strange i mostly write my dates as dd/mm/yy(yyyy) never use a dot or dash, so this would mean changing my ways when writing dates to suit!

I tested the dot and the dashed theory and although they do not display errors they still display the dates wrong:

See my attached image:
![screen shot 2013-07-11 at 09 19 25](https://f.cloud.github.com/assets/689184/780398/0459c1aa-ea03-11e2-9d9b-3ca527f6b904.png)

Within the title i have added the method of date entry and notice the published dates, with the dash '-' method they year and day get mixed and swopped where as with the dot syntax i would say only the day is incorrect but then testing it with say 16.08.14 will still revert to July 11th 2013 & time which basically is the exact time the entry was made although the times set are way into the future take the 16.08.14 gives me a published date of Jul 11th 2013, 05:08pm, which indicates to me that not setting the time it takes the  16 of the date if you notice in the image the dot versions the one on the 15.07.13 time is 04:07pm where as the 14.07.13 is an hour earlier 03:07pm

im not sure how many other people in the UK use the '/' but without notice it will cause then the error and an inundated amount of issues for the same thing, but perhaps some additional validation or notification under the input box to the format in light grey 'YY/MM/DD' or rather than an open input a date picker leaving the visual date to the users liking but in the background it being rearrange to suit the system.  I had the same issue before so i implemented the jquery datepicker to solve my problem.

Hope this is not out of order. Si

**Comment by ericlbarnes** [comment]
You may need to check your timezone setting in app/config/app.php. The default is UTC.

```
'timezone' => 'UTC',
```

I guess worst case just add yyyy-dd-mm which is the default mysql time. 

I will look into a date picker but I haven't one that allows date and time that I like.

**Comment by matalina** [comment]
Do you have a date picker?  Maybe a datepicker that formates in YYYY-MM-DD would be helpful.  I know for my in house projects instead of assuming they'll do it correctly cause YYYY-MM-DD is how all database dates get stored it allows me to make sure that they input it in correctly.  I beleive that the native date form type in HTML 5 will send YYYY-MM-DD back even if it's displayed different in the form field, at least that's my experience.

**Comment by ericlbarnes** [comment]
No wardrobe currently doesn't have any date picker plugins included. I haven't found any that I really like for picking both date and time. I think time is important and the reason I went with the current setup is so you could things like: 
- Tomorrow 10am
- Monday 1pm
- Next Wednesday 8am
- August 8th 5pm
- etc…

Of course with anything there are always positives and negatives and I really do feel the current setup is quicker and simpler for setting future dates than a clunky date/time picker. Just my opinion. 

-- Eric

On July 11, 2013 at 9:40:33 AM, Alicia (notifications@github.com) wrote:

Do you have a date picker? Maybe a datepicker that formates in YYYY-MM-DD would be helpful. I know for my in house projects instead of assuming they'll do it correctly cause YYYY-MM-DD is how all database dates get stored it allows me to make sure that they input it in correctly. I beleive that the native date form type in HTML 5 will send YYYY-MM-DD back even if it's displayed different in the form field, at least that's my experience.

**Comment by matalina** [comment]
completely understand.  time is always a 'b*_ch_.  jquery has a plugin that I use, but it's till 'clunky' if you ask me, but it makes the less tech saavy ppl put in things correctly formatted with out getting errors because they forgot to add in the seconds or whatever.

**Comment by simondavies** [comment]
Yeah I understand i am liking the text type of entry you have Monday 1pm This thursday 5pm etc its just that as an expected user i would not think about adding the published date as text like that but as you said this is down to preference and the user can customise it to their own means like carrying on adding in a datepicker like jQuery UI with a time section next to it the ideas gone on but I think what you have with a little of a note is a good starting point for the user and is different from the rest. If its going to be as stated a minimalistic blogging system then you should be up to the user to programe it how they want as this gives them a base.

Perhaps a consideration of a few with an option setting within the app.php or a detection of the timezone but hey Eric thanks for this

**Comment by ericlbarnes** [comment]
What do you guys/gals think of this idea?

Instead of a date picker we keep what I have. But when adding a post instead of defaulting to "now" it default to the current date/time. So something like "July 11 2013 08:04pm". 

My thinking behind this is that would prevent mistakes since it is shown and what I think most users would do is just edit the month and day leaving the rest. Or at least be used as a guide for how to format it. 

This would also keep the flexibility I mentioned above that I really like.

**Comment by rtablada** [comment]
I really like using the semantic English way that's built in. Definitely keep that!
—

**Comment by simondavies** [comment]
That sounds like a plan

**Comment by ericlbarnes** [comment]
Just found this which could be relevant. 
http://matthewmueller.github.io/date/

**Comment by simondavies** [comment]
Sorry been migraine weekend for me, that look interesting worth a further look
