### ISSUE TITLE
Upgrade Routine

### ISSUE THREAD

**Issue by ericlbarnes** [ericlbarnes/wardrobe#57]
I need to work on an easier upgrade routine.

**Comment by rtablada** [comment]
Yeah, I'm thinking that moving to a composer based package will make it super easy. Then you will be able to change the composer requirement version up a step and run composer update.

Essentially, the wardrobe/wardrobe would be a Laravel project shell that also requires wardrobe/framework and runs the config publish after composer install. This would make it so that you can create a wardrobe blog by running `composer create-project wardrobe/wardrobe`

What do you think of that path?

**Comment by ericlbarnes** [comment]
I think that sounds excellent. So it would need the config publish and then asset publish for the admin stuff. 

Would config publish over write? I guess that would matter so it doesn't need to be constantly changed. Or maybe just have config/wardrobe.php like this: 

```
<?php
include base_path('wardrobe.php');
```

So their settings would never get over written.

**Comment by rtablada** [comment]
Currently, I put asset publish within the installation process, although it could be run after composer install in the wardrobe/wardrobe project. Can't decide where would be best...

I liked it within the install process due to the fact that it allows customization within any Laravel project it is included in, but now that I think of it, it may be better to pull the installation out and framework only works on the admin section and post views? Then installation would be moved to the wardrobe project?

Don't know, just thinking out loud.

**Comment by sheldonkotyk** [comment]
I'm really looking forward to the move to a composer package. I'm just wondering if it will be an upgrade path from the current installation or if I will need to do a major conversion. I'm just debating whether to go live with my blog now or wait.

**Comment by rtablada** [comment]
It will likely require some decent overhaul, but you can start now and save your DB and template as they should work in the future version.

I have been running Wardrobe since day 1 and have loved how much it frees me up to write in comparison to other CMS/Blog platforms (even the simple ones)...

I'm trying to document any breaking changes to template helpers as I go and will be likely updating the current repo with those changes.

**Comment by ericlbarnes** [comment]
@rtablada Should we break this into two repos just like laravel/framework and laravel/laravel.  Maybe wardrobe/core and wardobe/wardrobe? 

The wardrobe/wardrobe would be basically a stock l4 repo with the wardrobe/core as a composer package? 

I am thinking about moving this to the https://github.com/wardrobecms/ project instead of under my own. That way I think adding a team would be easier.

**Comment by rtablada** [comment]
Yeah that's what I was thinking.

Wardrobe/wardrobe will be an L4 skeleton with the installer.

Wardrobe/core will be everything else as a package.

**Comment by rtablada** [comment]
@ericbarnes if you want we could Skype pair or something soon to work on the move?

**Comment by ericlbarnes** [comment]
Sounds good. userscape.eric is mine.
